from enum import Enum

class ResponseSignal(Enum):
   FILE_VALIDATED_SUCCESS = "FILE_VALIDATED_SUCCESS"
   FILE_TYPE_NOT_SUPPORTED = "FILE_TYPE_NOT_SUPPORTED"
   FILE_SIZE_TOO_LARGE = "FILE_SIZE_TOO_LARGE"
   FILE_UPLOAD_SUCCESS = "FILE_UPLOAD_SUCCESS"
   FILE_UPLOAD_FAILED = "FILE_UPLOAD_FAILED"
